#!/bin/bash

results=./results.dat
rm -f $results

for ion in acet esna mso4 guan imim mamm
do
    cd $ion

    last_line=$(tail ./integral.dat -n 1)
    echo $ion $last_line | awk '{printf "%-12s%15.10f%20.12f\n", $1, $3, $4}' >> ../${results}

    cd ../
done




