#!/bin/bash
# Python 2

eval "$(conda shell.bash hook)"
conda activate py2

for ion in acet esna mso4 guan imim mamm
do
    cd $ion

    ln -sf ../utilities/process_seven_point.py ./
    ln -sf ../utilities/7p_integral.py ./
    ln -sf ../utilities/extract_column ./
    ln -sf ../utilities/block_averaging_replacement.py ./
    cp ../utilities/input ./

    python process_seven_point.py 0
    python 7p_integral.py force.dat > integral.dat

    cd ../
done

conda deactivate
