#!/bin/bash
# NOTE:  this requires python 2

pair=$1

base_name="equilibrate"

mkdir -p $pair
cd $pair
        
base_path=../../equilibrate/${pair}
cp ${base_path}/equilibrate.coor ./
cp ${base_path}/system.psf ./
cp ${base_path}/equilibrate.restart.xsc ./

python ../utilities/fix_charge.py [AION,CION] 3 system.psf

for lambda in 0.1127 0.5000 0.8873
do
    folder=q_${lambda}
    mkdir -p $folder
    cd $folder

    echo s/xx_psf_file_xx/scaled_${lambda}/g > ./tmp
    echo s/xx_job_id_xx/${folder}/g >> ./tmp
    echo s/xx_base_name_xx/${base_name}/g >> ./tmp

    sed -f ./tmp ../../files/charging_template.namd > ./charging.namd
    sed -f ./tmp ../../files/get_energy_template.namd > ./get_energy.namd
    cp ../../files/runme_charging ./
    cp ../../files/runme_get_energy ./

    cd ../
done
cd ../
