#!/bin/bash

eval "$(conda shell.bash hook)"
conda activate py2

previous_radius=4.9745550
radius_rounded=$(echo $previous_radius | awk '{printf "%.4f", $1}') # 4 decimal float
base_name=wbigbox_${radius_rounded}
new_radius=$(echo $previous_radius | awk '{print int($1+0.5)}').0 # nearest whole number

for ion in acet esna mso4 guan imim mamm
do
    mkdir -p $ion
    cd $ion

    base_path=../../b_chemistry_with_charges/${ion}
    cp ${base_path}/${base_name}.coor ./
    cp ${base_path}/${base_name}.restart.coor ./
    cp ${base_path}/${base_name}.restart.vel ./
    cp ${base_path}/${base_name}.restart.xsc ./
    cp ${base_path}/system.psf ./
    cp ${base_path}/residuebased.zero.tcl ./

    python ../utilities/fix_charge.py [AION,CION] 3 system.psf
    python ../utilities/fix_charge.py [AION,CION] 0 system.psf

    for lambda in 0.0000 0.1127 0.5000 0.8873
    do
        folder=q_${lambda}
        mkdir -p $folder
        cd $folder

        echo s/xx_previous_radius_xx/${previous_radius}/g > ./tmp
        echo s/xx_new_radius_xx/${new_radius}/g >> ./tmp
        echo s/xx_job_id_xx/${folder}/g >> ./tmp
        echo s/xx_base_name_xx/${base_name}/g >> ./tmp
        echo s/xx_psf_file_xx/scaled_${lambda}/g >> ./tmp
        echo s/xxx_ion_xxx/${ion}/g >> ./tmp
        echo s/xxx_lambda_xxx/${lambda}/g >> ./tmp

        sed -f ./tmp ../../files/charging_template.namd > ./charging.namd
        sed -f ./tmp ../../files/get_energy_template.namd > ./get_energy.namd
        sed -f ./tmp ../../files/runme_charging.lsf > ./runme_charging.lsf
        # sed -f ./tmp ../../files/runme_get_energy.lsf > ./runme_get_energy.lsf
        cp ../../files/runme_get_energy_local.sh .

        rm ./tmp

        cd ../
    done
    cd ../
done

conda deactivate
