#!/bin/bash

eval "$(conda shell.bash hook)"
conda activate py2

results=./results.dat
rm -f $results

for ion in acet esna mso4 guan imim mamm
do
    cd $ion
    rm -f block_average.dat

    for lambda in 0.1127 0.5000 0.8873
    do
        folder=q_${lambda}
        cd $folder

        egrep '^ENERGY:' get_energy.log | awk '{printf("%d %f\n",$2,$7)}' | tail -n 4000 > out1 # taking 4/5 of data - discarding first 0.2 ns
        cp ../../files/input.Nozaki ./input
        /home/chase/codes/stat_gr < input >> ../block_average.dat

        cd ../
    done

    python ../utilities/three_point_integral.py block_average.dat > results_charging.dat
    last_line=$(cat results_charging.dat)
    echo $ion $last_line | awk '{printf "%-12s%15.10f%20.12f\n", $1, $3, $4}' >> ../${results}

    cd ../
done

conda deactivate
