#!/bin/bash
# Python 3

conformer=$1
pair=$2

cd $conformer
# Make a .pdb file with only the solute species
awk '! /SOLV/ {print}' equilibrate.coor > just_solutes.pdb

# Get the corresponding (previously-generated) .psf files
cp ../../../abf_no_salt/${pair}/just_solutes.psf ./

# Get average simulation box lengths
for lambda in 0.1127 0.5000 0.8873
do
    folder=q_${lambda}
    cd $folder

    ln -sf ../../utilities/block_averaging_functions.py
    ln -sf ../../utilities/get_box_length.py
    python get_box_length.py ${folder}.dcd ../scaled_${lambda}.psf

    cd ../
done

ln -sf ../utilities/get_box_length_average.py
python get_box_length_average.py

cd ../







